"""Short everyday situations for the story quiz: "How might they feel?"

Practising how situations lead to feelings (perspective-taking) complements reading faces,
and it works without any photos. Each item has the most likely feeling and a one-line
explanation. ``also`` lists other reasonable answers for genuinely ambiguous situations:
the activity teaches perspective-taking, not that every situation has one compulsory feeling.
Wording is kept simple, concrete and kind.
"""

SCENARIOS = [
    # happiness
    {"text": "Mia's grandma comes to visit and brings Mia's favourite cookies.", "answer": "happiness",
     "why": "Seeing someone you love and getting a treat usually makes people happy."},
    {"text": "Leo's team scores the winning goal at the end of the game.", "answer": "happiness",
     "why": "Winning after trying hard feels great."},
    {"text": "Aria finally learns to ride her bike without help.", "answer": "happiness",
     "why": "Doing something new by yourself makes people proud and happy."},
    {"text": "Sam's friend shares half of their sandwich with him at lunch.", "answer": "happiness",
     "why": "When someone is kind to us, we often feel happy."},
    {"text": "It's the first sunny day of summer and Noor is going to the beach.", "answer": "happiness",
     "why": "Going somewhere fun that you were looking forward to feels happy."},
    {"text": "Kai's teacher puts a gold star on his drawing.", "answer": "happiness",
     "why": "Being praised for our work usually makes us happy."},
    # sadness
    {"text": "Zoe's best friend is moving to another city.", "answer": "sadness",
     "why": "Saying goodbye to someone we care about often makes us sad."},
    {"text": "Omar's ice cream falls on the ground right after he buys it.", "answer": "sadness",
     "why": "Losing something we were enjoying can make us sad."},
    {"text": "Lily's pet fish has died.", "answer": "sadness",
     "why": "When a pet dies, people feel sad because they miss it."},
    {"text": "Ben was not invited to a classmate's party, but everyone else was.", "answer": "sadness",
     "why": "Feeling left out often makes people sad."},
    {"text": "It rains all day, so Ivy's trip to the park is cancelled.", "answer": "sadness", "also": ["anger"],
     "why": "When a plan we were excited about is cancelled, we can feel sad or disappointed."},
    {"text": "Theo loses his favourite teddy bear and can't find it anywhere.", "answer": "sadness",
     "why": "Losing something special usually makes people sad."},
    # anger
    {"text": "Someone knocks over the tower Maya spent an hour building, on purpose.", "answer": "anger",
     "why": "When someone ruins our work on purpose, we often feel angry."},
    {"text": "Jay's brother takes his toy without asking and won't give it back.", "answer": "anger",
     "why": "When someone takes our things unfairly, we can feel angry."},
    {"text": "A kid cuts in front of Rosa in the lunch line.", "answer": "anger",
     "why": "When something feels unfair, people often feel angry."},
    {"text": "Ali is blamed for breaking a vase that his cousin broke.", "answer": "anger",
     "why": "Being blamed for something you didn't do usually makes people angry."},
    {"text": "Someone keeps kicking the back of Ella's chair during the movie.", "answer": "anger",
     "why": "When someone keeps bothering us after we asked them to stop, we can feel angry."},
    {"text": "Finn's classmate copies his answers and gets the credit.", "answer": "anger",
     "why": "When someone takes credit for our work, it feels unfair and can make us angry."},
    # fear
    {"text": "Nina hears a loud crash of thunder in the middle of the night.", "answer": "fear",
     "why": "Sudden loud noises in the dark can make people feel scared."},
    {"text": "Max gets lost in a big, crowded shopping mall.", "answer": "fear",
     "why": "Being lost and alone can make people feel scared."},
    {"text": "A big dog runs toward Priya, barking loudly.", "answer": "fear",
     "why": "When something might hurt us, we often feel scared."},
    {"text": "Eli has to go to the dentist for the first time.", "answer": "fear", "also": ["neutral"],
     "why": "New things we don't know about can feel scary."},
    {"text": "Hana is standing at the top of a very tall slide.", "answer": "fear", "also": ["happiness"],
     "why": "Being up high can make people feel scared or nervous."},
    {"text": "The lights suddenly go out and the house is completely dark.", "answer": "fear",
     "why": "Not being able to see what's around us can feel scary."},
    # surprise
    {"text": "Lucas walks into the room and everyone shouts \"Happy birthday!\"", "answer": "surprise",
     "why": "Something we didn't expect at all makes us surprised."},
    {"text": "Sara opens a box and a toy snake pops out.", "answer": "surprise",
     "why": "Something sudden and unexpected makes people surprised."},
    {"text": "Tom's dad comes home from a long trip a day early.", "answer": "surprise", "also": ["happiness"],
     "why": "When something happens sooner than we expected, we feel surprised (and often happy too)."},
    {"text": "It starts snowing in the middle of spring.", "answer": "surprise",
     "why": "When something unusual happens, people feel surprised."},
    {"text": "Ruby finds a $10 note in an old coat pocket.", "answer": "surprise",
     "why": "Finding something we didn't know about makes us surprised."},
    {"text": "A magician pulls a rabbit out of an empty hat.", "answer": "surprise",
     "why": "When something seems impossible, we feel surprised."},
    # disgust
    {"text": "Jack smells the milk and it has gone sour.", "answer": "disgust",
     "why": "Bad smells often make people feel disgusted."},
    {"text": "Emma finds a hair in her soup.", "answer": "disgust",
     "why": "Finding something gross in food usually makes people feel disgusted."},
    {"text": "Noah steps in something squishy and smelly on the grass.", "answer": "disgust",
     "why": "Touching something yucky makes people feel disgusted."},
    {"text": "Grace sees a worm in the apple she just bit.", "answer": "disgust",
     "why": "Finding a bug in food makes most people feel disgusted."},
    {"text": "The school bathroom is really dirty and smelly.", "answer": "disgust",
     "why": "Dirty, smelly places often make people feel disgusted."},
    {"text": "Adam's little brother sneezes all over the dinner table.", "answer": "disgust",
     "why": "Germs and mess on our food can make us feel disgusted."},
    # neutral / calm
    {"text": "Liam is sitting on the bus, looking out of the window on the way to school.", "answer": "neutral",
     "why": "During ordinary, everyday moments, people often feel calm."},
    {"text": "Ava is brushing her teeth before bed, like every night.", "answer": "neutral",
     "why": "Usual routines often make people feel calm."},
    {"text": "Ethan is reading a book quietly in the library.", "answer": "neutral",
     "why": "Quiet, peaceful activities often make people feel calm."},
    {"text": "Chloe waits for the kettle to boil.", "answer": "neutral",
     "why": "Waiting for something ordinary usually doesn't bring a strong feeling."},
    {"text": "Ryan is folding his clean clothes and putting them away.", "answer": "neutral",
     "why": "Simple chores often leave people feeling calm."},
    {"text": "Mila is walking to the shop to buy bread, like she does every Saturday.", "answer": "neutral",
     "why": "Familiar, everyday tasks often feel calm."},
]
